import messages from "@/app/messages";
import AddUserGroup from "@/src/components/screens/chat/component/AddUserGroup";

export const VnLocalizedStrings = {
  Public: {
    All: "Tất cả",
    Confirm: "Xác nhận",
    Cancel: "Hủy",
    Back: "Quay lại",
    Save: "Lưu",
    Close: "Đóng",
    Language: "Ngôn ngữ: Tiếng Việt",
    Post: "Bài Viết",
    Friend: "Bạn Bè",
    Username: "Tên người dùng",
    About: "Giới Thiệu",
    Today: "Hôm nay bạn thế nào?",
    Detail: "Chi tiết",
    EditProfile: "Chỉnh sửa trang cá nhân",
    ChangePassword: "Thay đổi mật khẩu",
    LogOut: "Đăng xuất",
    SetingProfile: "Cài đặt",
    Mail: "Email",
    Phone: "Số điện thoại",
    Birthday: "Ngày sinh",
    Active: "Ngày tham gia",
    FriendFind: "Tìm bạn bè",
    FriendView: "Xem tất cả bạn bè",
    Conform: "Xác nhận",
    LogoutConfirm: "Bạn có chắc chắn muốn đăng xuất",
    More: "Xem thêm",
    AddFriend: "Kết bạn",
    UnFriend: "Hủy kết bạn",
    CancelFriendRequest: "Hủy lời mời",
    RefuseFriendRequest: "Từ chối",
    AcceptFriendRequest: "Chấp nhận",
    ReportFriend: "Báo Cáo",
    Block: "Chặn",
    Vietnamese: "Tiếng Việt",
    English: "Tiếng Anh",
    ErrorFetchingProfile: "Lỗi hiển thị thông tin",
    Biography: "Giới thiệu",
    UnknownUser: "Người dùng YourVibes",
    Public: "Công khai",
    Everyone: "Mọi người",
    Private: "Chỉ mình tôi",
    MinuteAgo: "phút trước",
    HourAgo: "giờ trước",
    DayAgo: "ngày trước",
    Action: "Hành động",
    CommonActions: "Nhập bình luận của bạn ...",
    Comment: "Bình luận",
    Reply: "Trả lời",
    ReportComment: "Báo cáo bình luận",
    Day: "Ngày",
    ListUserLikePost: "Danh sách người thích bài viết",
    WhoLike: "Khám phá ai đã thích bài viết!",
    HideInfo: "đã ẩn thông tin cá nhân",
    FriendOnly: "chỉ bạn bè được xem",
    Trending: "Xu hướng",
    BirthdayFriend: "Sinh nhật bạn bè",
    NewFeed: "Bảng tin",
    NoBirthdays: "Không có ngày sinh nhật nào",
    HappyBirthday:
      "Hãy gửi lời chúc mừng sinh nhật đến những người bạn của bạn!",
    FriendRequests: "Lời mời kết bạn",
    Theme: "Chế độ",
    DarkMode: "Chế độ tối",
    LightMode: "Chế độ sáng",
    AllUser: "Người dùng YourVibes",
    UserNotFound: "Không tìm thấy người dùng",
  },
  Form: {
    Label: {
      Email: "Email",
      Password: "Mật khẩu",
      FamilyName: "Họ",
      Name: "Tên",
      Phone: "Số điện thoại",
      BirthDay: "Ngày sinh",
      GetOTP: "Nhập OTP",
      OTP: "Mã OTP",
      ConfirmPassword: "Xác nhận mật khẩu",
      Biography: "Tiểu sử",
    },
    RequiredMessages: {
      FamilyNameRequiredMessage: "Vui lòng nhập họ!",
      NameRequiredMessage: "Vui lòng nhập tên!",
      PhoneRequiredMessage: "Vui lòng nhập số điện thoại!",
      BirthDayRequiredMessage: "Vui lòng chọn ngày sinh!",
      EmailRequiredMessage: "Vui lòng nhập email!",
      PasswordRequiredMessage: "Vui lòng nhập mật khẩu!",
      ConfirmPasswordRequiredMessage: "Vui lòng xác nhận mật khẩu!",
      AgreeRequiredMessage: "Vui lòng đồng ý các điều khoản!",
      OTPRequiredMessage: "Vui lòng nhập mã OTP!",
      OTPPressRequiredMessage: "Vui lòng nhận mã OTP!",
    },
    TypeMessage: {
      EmailTypeMessage: "Email không hợp lệ!",
      PasswordTypeMessage: "Mật khẩu phải trên 8 kí tự!",
      ConfirmPasswordTypeMessage: "Xác nhận mật khẩu không hợp lệ!",
      OTPTypeMessage: "Mã OTP phải là chuỗi 6 số!",
      PhoneTypeMessage: "Số điện thoại phải là chuỗi 10 số!",
      PleaseOldPasswordDifferentNewPassword:
        "Mật khẩu mới phải khác mật khẩu cũ!",
    },
  },
  Login: {
    LoginButton: "Đăng nhập",
    ForgotPasswordText: "Quên mật khẩu?",
    DontHaveAccout: "Bạn chưa có tài khoản?",
    SignUpNow: "Đăng ký ngay!",
    Or: "Hoặc",
    LoginFailed: "Đăng nhập thất bại!",
  },
  SignUp: {
    SignUpButton: "Đăng ký",
    SignUpSuccess: "Đăng ký thành công! Vui lòng đăng nhập lại",
    SignUpFailed: "Đăng ký thất bại!",
    OTPSuccess: "OTP đã được gửi thành công!",
    OTPAlreadySent: "Mã OTP đã được gửi và tồn tại trong 10 phút!",
    OTPFailed: "Gửi OTP thất bại!",
    AlreadyHaveAccount: "Bạn đã có tài khoản?",
    LoginNow: "Đăng nhập ngay!",
    AgreePolicies: "Tôi đồng ý các điều khoản của YourVibes",
  },
  AddPost: {
    NewPost: "Bài đăng mới",
    WhatDoYouThink: "Bạn đang nghĩ gì?",
    PrivacyText: "Bài đăng được chia sẻ với",
    PostNow: "Đăng ngay",
    CreatePostSuccess: "Đăng bài thành công!",
    CreatePostFailed: "Đăng bài thất bại!",
    EmptyContent: "Thiếu nội dung hoặc file media",
    PickImgFailed: "Tải file thất bại!",
    CensorPost: "Bài viết của bạn đang được kiểm duyệt, vui lòng chờ.",
  },
  ObjectPostPrivacy: {
    PublicDescription: "Bất kỳ ai ở trên YourVibes",
    FriendDescription: "Chỉ bạn bè của bạn ở trên YourVibes",
    PrivateDescription: "Chỉ bạn có thể nhìn thấy",
    PostPrivacy: "Quyền riêng tư của bài viết",
    Contents: {
      WhoCanSee: "Ai có thể nhìn thấy bài viết của bạn?",
      CanFind:
        "Bài viết của bạn có thể hiện thị trên trang cá nhân và trong kết quả tìm kiếm.",
      DefaultPrivacy1: "Tuy đối tượng mặc định là ",
      DefaultPrivacy2:
        ", nhưng bạn có thể thay đổi Quyền riêng tư của riêng bài viết này.",
    },
    ChoosePrivacy: "Chọn Đối tượng",
  },
  ObjectProfile: {
    ProfilePrivacy: "Quyền riêng tư của thông tin cá nhân",
    Contents: {
      WhoCanSee: "Ai có thể nhìn thấy thông tin của bạn?",
      DefaultPrivacy2:
        ", nhưng bạn có thể thay đổi quyền riêng tư cho thông tin tài khoản của mình.",
    },
  },
  Post: {
    EditPost: "Chỉnh sửa bài đăng",
    EditPrivacy: "Chỉnh sửa quyền riêng tư",
    DeletePost: "Xóa bài đăng",
    Advertisement: "Quảng cáo bài đăng",
    ReportPost: "Báo cáo bài đăng",
    LikePostFailed: "Thích bài viết thất bại!",
    SharePostSuccess: "Chia sẻ bài viết thành công!",
    SharePostFailed: "Chia sẻ bài viết thất bại!",
    SharePost: "Chia sẻ",
    DeleteNewFeed: "Ẩn bài viết",
    NoContent: "Nội dung không tồn tại!",
    NoContentDetail:
      "Nội dung đã bị xoá hoặc cài đặt quyền riêng tư bởi người dùng!",
    Sponsor: "Được tài trợ",
    NoTrendingPosts: "Chưa có bài viết trending nào",
  },
  PostDetails: {
    ViewReplies: "Xem phản hồi",
    HideReplies: "Ẩn phản hồi",
    Save: "Lưu",
    Cancel: "Hủy",
    Error: "Lỗi",
    ErrorReplies: "Lỗi phản hồi",
    ReportComment: "Báo cáo bình luận",
    EditComment: "Chỉnh sửa bình luận",
    DeleteComment: "Xóa bình luận",
    ActionOptions: "Chọn hành động",
    ReportSusesfully: "Báo cáo bình luận thành công!",
    Success: "Thành công",
    EditCommentSuccess: "Cập nhật bình luận thành công!",
    EditCommentFailed: "Cập nhật bình luận thất bị!",
    EditReplySuccess: "Cập nhật phản hồi thành công!",
    EditReplyFailed: "Cập nhật phản hồi thất bại!",
    DeteleReplyFailed: "Xóa phản hồi thất bại!",
    DeteleReplySuccess: "Xóa phản hồi thành công!",
    CommentSuccess: "Bình luận thành công!",
    CommentFailed: "Bình luận thất bại!",
    ReplySuccess: "Phản hồi thành công!",
    ReplyFailed: "Phản hồi thất bại!",
    Yes: "Xác nhận",
    No: "Không",
    CommentNotFound: "Không tìm thấy bình luận!",
  },
  Profile: {
    Posts: {
      GetPostsFailed: "Lấy danh sách bài viết thất bại!",
      GetOnePostFailed: "Lấy bài viết thất bại!",
    },
    Info: {
      GetInfoFailed: "Lấy thống tin người dùng thất bại!",
    },
    Friend: {
      SendYouARequest: "Đã gửi cho bạn một lời mời kết bạn!",
      SendARequest: "Đã gửi lời mời kết bạn!",
      SendRequestFailed: "Gửi lời mời kết bạn thất bại!",
      SendRequestSuccess: "Gửi lời mời kết bạn thành công!",
      FriendResponseFailed: "Phản hồi lời mời thất bại!",
      FriendResponseSuccess: "Phản hồi lời mời thành công!",
      CancelRequestFailed: "Hủy lời mời thất bại!",
      CancelRequestSuccess: "Hủy lời mời thành công!",
      UnfriendFailed: "Hủy kết bạn thất bại!",
      UnfriendSuccess: "Hủy kết bạn thành công!",
      UnfriendConfirm: "Bạn có muốn hủy kết bạn với người dùng này?",
    },
  },
  UpdatePost: {
    UpdatePostSuccess: "Cập nhật bài đăng thành công!",
    UpdatePostFailed: "Cập nhật bài đăng thất bại!",
  },
  DeletePost: {
    DeleteConfirm: "Bạn chắc chắn muốn xóa bài viết này?",
    DeleteSuccess: "Xóa bài viết thành công!",
    DeleteFailed: "Xóa bài viết thất bại!",
  },
  UpdateProfile: {
    UpdateProfile: "Cập nhật trang cá nhân",
    UpdateFailed: "Cập nhật trang cá nhân thất bại!",
    UpdateSuccess: "Cập nhật trang cá nhân thành công!",
  },
  Search: {
    Search: "Tim kiếm",
    SearchPlaceholder: "Bạn đang tìm gì...",
    SearchFailed: "Tìm kiếm thất bại!",
    NoUsers: "Không tìm thấy người dùng",
    TrySearch: "Hãy nhập từ khóa cần tìm",
  },
  Notification: {
    Notification: "Thông báo",
    NoNotification: "Không có thông báo",
    Items: {
      LikePost: "đã thích bài viết của bạn: ",
      SharePost: "đã chia sẻ bài viết của bạn: ",
      CommentPost: "đã bình luận về bài viết của bạn: ",
      Friend: "đã gửi lời mời kết bạn.",
      AcceptFriend: "đã chấp nhận lời mời kết bạn của bạn.",
      NewPost: "đã đăng một bài viết mới.",
      LikeComment: "đã thích bình luận của bạn: ",
      NewPostPersonal: "bài viết của bạn đăng thành công:",
      NewPostError: "bài viết của bạn bị lỗi",
      BlockCreatePost: "bài viết của bạn đã bị chặn",
      nsfw: "vì chứa nội dung nhạy cảm",
      political: "vì chứa nội dung chính trị không phù hợp",
      violence: "vì chứa nội dung bạo lực",
      abuse: "vì chứa nội dung xâm hại trẻ em",
      DeactivatePostContent:
        "bài viết của bạn đã bị chặn vì vi phạm các điều khoản và điều kiện của chúng tôi. Nếu bạn nghĩ rằng đây là một sai lầm, vui lòng liên hệ với bộ phận hỗ trợ của chúng tôi để được xem xét lại.",
      ActivacePostContent:
        "bài viết của bạn đã được kích hoạt lại sau khi xem xét. Cảm ơn bạn đã kiên nhẫn chờ đợi.",
      DeactivateCommentContent:
        "bình luận của bạn đã bị chặn vì vi phạm các điều khoản và điều kiện của chúng tôi. Nếu bạn nghĩ rằng đây là một sai lầm, vui lòng liên hệ với bộ phận hỗ trợ của chúng tôi để được xem xét lại.",
      ActivaceCommentContent:
        "bình luận của bạn đã được kích hoạt lại sau khi xem xét. Cảm ơn bạn đã kiên nhẫn chờ đợi.",
      NewMessage: "Có tin nhắn mới.",
    },
  },
  ListFriends: {
    ListFriends: "Danh sách bạn bè",
    Search: "Tim kiếm . . .",
    ViewProfile: "Xem trang cá nhân",
    Unfriend: "Hủy kết bạn ",
    Block: "Chặn ",
    Cancel: "Hủy",
  },
  Ads: {
    Ads: "Quảng cáo bài viết",
    TimeAndBudget: "Khoảng thời gian và Ngân sách",
    Minimum: "Tối thiểu: {{price}}/1 ngày (Tối đa: 30 ngày)",
    DaysAds: "Số ngày quảng cáo:",
    TimeAds: "Thời gian quảng cáo: ",
    BudgetAds: "Ngân sách: ",
    PaymentMethod: "Phương thức thanh toán",
    AdvertisePostFailed: "Quảng cáo bài viết thất bại!",
    AdvertisePostSuccess: "Quảng cáo bài viết thành công!",
    ActiveCampaign: "Chiến dịch đang thực hiện",
    HideCampaign: "Ẩn lịch sử các chiến dịch",
    ShowCampaign: "Xem lịch sử các chiến dịch",
    Campaign: "Chiến dịch",
    End: "Kết thúc",
    RemainingTime: "Thời gian còn lại",
    Day: "Ngày",
    Grant: "Kinh phí",
    Status: "Trạng thái",
    PaymentSuccess: "Thanh toán thành công",
    PaymentFailed: "Thanh toán thất bại",
    NoCampaign: "Không có chiến dịch nào",
  },
  Report: {
    ReportPost: " Tại sao bạn báo cáo bài viết này?",
    ReportUser: "Tại sao bạn báo cáo người dùng này?",
    ReportComment: "Tại sao bạn báo cáo bình luận này?",
    ReportSuccess: "Báo cáo thành công!",
    ReportFailed: "Báo cáo thất bại!",
    Note: "Nếu bạn nhận thấy sự đe dọa hoặc ai đó dang gặp nguy hiểm, đừng chần chừ mà hãy tìm ngay sự giúp đỡ và báo cho dịch vụ khẩn cấp ở địa phương trước khi báo cáo với YourVibes.",
  },
  ChangePassword: {
    ChangePassword: "Thay đổi mật khẩu",
    ChangePasswordFailed: "Thay đổi mật khẩu thất bại!",
    ChangePasswordSuccess: "Thay đổi mật khẩu thành công!",
    OldPassword: "Mật khẩu cũ",
    NewPassword: "Mật khẩu mới",
    ConformPassword: "Xác nhận mật khẩu mới",
    Email: "Email",
    SendOTP: "Nhận OTP",
    OTP: "Mã OTP",
    ConformChangePassword: "Xác nhận thay đổi mật khẩu",
  },
  webSocker: {
    WebSocketConnected: "Web Socket đã kết nối",
    WebSocketDisconnected: "Web Socket đã ngắt kết nối",
    WebSocketError: "Lỗi Web Socket",
    WebSocketErrorText: "Vui lòng kiểm tra kết nối mạng của bạn",
  },
  ForgotPassword: {
    ConformChangePasswordSuccess: "Thay đổi mật khẩu thành công!",
    ConformChangePasswordFailed: "Thay đổi mật khẩu thất bại!",
  },
  Messages: {
    CreateGroup: "Tạo nhóm",
    Messages: "Tin nhắn",
    Admin: "Chủ phòng",
    EnterMessage: "Nhập tin nhắn",
    Member: "Thành viên",
    DeleteMember: "Xoá thành viên",
    Reply: "Trả lời",
    AddUserGroup: "Thêm thành viên",
    DeleteConversation: "Xóa cuộc trò chuyện",
    LeaveGroup: "Rời khỏi nhóm",
    DeleteConversationConfirm: "Bạn có chắc chắn muốn xóa cuộc trò chuyện này?",
    LeaveGroupConfirm: "Bạn có chắc chắn muốn rời khỏi nhóm này?",
    CantLeaveGroup:
      "Vui lòng chuyển quyền chủ phòng cho người khác trước khi rời nhóm",
    CantDeleteGroup: "Chỉ chủ phòng có quyền xóa nhóm này",
    Today: "Hôm nay",
    Yesterday: "Hôm qua",
    NameGroup: "Vui lòng nhập tên nhóm!",
    NameGroupPlaceholder: "Tên nhóm",
    InfoGroup: "Thông tin nhóm",
  },
  Suggested: {
    SuggestedFriends: "Những người bạn có thể biết",
    Hide: "Ẩn",
    SeeMore: "Xem thêm",
    Why: "Tại sao tôi lại thấy những người bạn này?",
    Dont: "Tôi không muốn thấy những người bạn này",
    AddFriend: "Kết bạn",
    FriendRequestSent: "Đã gửi..",
    WhyExplanation: "Những gợi ý này dựa trên các yếu tố như:",
    WhyFactor1: "Bạn bè chung",
    WhyFactor2: "Sở thích tương đồng",
    WhyFactor3: "Hoạt động gần đây trên mạng xã hội",
    WhyConclusion:
      "Chúng tôi sử dụng thuật toán để tìm những người bạn có thể quen biết hoặc muốn kết nối!",
  },
  People: {
    People: "Mọi người",
    FetchUsersFailed: "Tải danh sách người dùng thất bại",
    ErrorFetchingUsers: "Lỗi khi tải danh sách người dùng",
    NoFriendRequests: "Không có lời mời kết bạn nào",
    ErrorFriendRequests: "Lỗi khi tải danh sách lời mời kết bạn",
    AcceptScuccess: "Chấp nhận lời mời thành công",
    AcceptFailed: "Chấp nhận lời mời thất bại",
    AcceptError: "Lỗi khi chấp nhận lời mời",
    DeclineSuccess: "Từ chối lời mời thành công",
    DeclineFailed: "Từ chối lời mời thất bại",
    DeclineError: "Lỗi khi từ chối lời mời",
    FriendRequestSent: "Đã gửi lời mời kết bạn",
    FriendRequestSentError: "Lỗi khi gửi lời mời kết bạn",
    FriendRequestSentSuccess: "Gửi lời mời kết bạn thành công",
    FriendRequestCanceled: "Đã hủy lời mời kết bạn",
    FriendRequestCanceledError: "Lỗi khi hủy lời mời kết bạn",
    FriendRequestCanceledSuccess: "Hủy lời mời kết bạn thành công",
    FriendRequestSentFailed: "Gửi lời mời kết bạn thất bại",
    FriendRequestCanceledFailed: "Hủy lời mời kết bạn thất bại",
  },
};
